# Generated by Django 4.2.28 on 2026-02-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='Иконка (SVG или класс)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании / Имя')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение / Услуга')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки уведомления')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Посещения')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Уникальные посетители')),
                ('applications', models.PositiveIntegerField(default=0, verbose_name='Заявки')),
            ],
            options={
                'verbose_name': 'Ежедневная статистика',
                'verbose_name_plural': 'Ежедневная статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=200, verbose_name='Страница')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='Источник')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время посещения')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('icon', models.CharField(blank=True, help_text='SVG код или CSS класс иконки', max_length=500, verbose_name='Иконка (SVG или класс)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Альтер Серт', max_length=100, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('hero_title', models.CharField(default='Профессиональная Сертификация и Легализация', max_length=200, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.TextField(default='Ваш надёжный партнёр в мире сертификации. Полное соответствие законодательству и регламентам.', verbose_name='Подзаголовок Hero')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Изображение Hero')),
                ('hero_button_primary', models.CharField(default='Рассчитать стоимость', max_length=50, verbose_name='Текст основной кнопки')),
                ('hero_button_secondary', models.CharField(default='Получить консультацию', max_length=50, verbose_name='Текст вторичной кнопки')),
                ('hero_badge_1', models.CharField(default='100% Легально', max_length=50, verbose_name='Бейдж 1')),
                ('hero_badge_2', models.CharField(default='Быстрее на 40%', max_length=50, verbose_name='Бейдж 2')),
                ('services_title', models.CharField(default='Наши Услуги', max_length=100, verbose_name='Заголовок услуг')),
                ('services_subtitle', models.TextField(default='Полный спектр услуг по легализации продукции. От разработки документов до получения сертификатов.', verbose_name='Подзаголовок услуг')),
                ('why_us_title', models.CharField(default='Почему Альтер Серт?', max_length=100, verbose_name='Заголовок "Почему мы"')),
                ('why_us_subtitle', models.TextField(default='Мы объединили многолетний опыт экспертов и передовые технологии для вашего спокойствия.', verbose_name='Подзаголовок "Почему мы"')),
                ('how_it_works_title', models.CharField(default='Как мы работаем', max_length=100, verbose_name='Заголовок "Как мы работаем"')),
                ('contact_title', models.CharField(default='Оставить заявку', max_length=100, verbose_name='Заголовок контактов')),
                ('contact_subtitle', models.TextField(default='Заполните форму, и мы свяжемся с вами в течение 15 минут для расчёта стоимости.', verbose_name='Подзаголовок контактов')),
                ('footer_text', models.TextField(default='Ваш надёжный партнёр в мире сертификации. Полное соответствие регламентам.', verbose_name='Текст в футере')),
                ('address', models.CharField(default='г. Москва, ул. Примерная, д. 10, оф. 305', max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(default='+7 (495) 000-00-00', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@altersert.ru', max_length=254, verbose_name='Email')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер этапа')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['number'],
            },
        ),
    ]
